#include "unittest/framework/TestSuite.h"
#include "jsonserialization/JSONDeserializationContext.h"

static void testInit() {
	JSONDeserializationContext context, * contextPtr;
	struct JSONNode node;
	
	node.type = JSON_TYPE_ARRAY;
	node.value.count = 0;
	node.subitems = NULL;
	
	memset(&context, 0, sizeof(context));
	JSONDeserializationContext_initWithString(&context, "", 0);
	TestCase_assert(context.jmpBuf == NULL, "Expected NULL but got %p", context.jmpBuf);
	TestCase_assert(context.status == SERIALIZATION_ERROR_OK, "Expected %d but got %d", SERIALIZATION_ERROR_OK, context.status);
	TestCase_assert(context.dispose != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readFloat != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readDouble != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readString != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBoolean != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readEnumeration != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readNextDictionaryKey != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.hasDictionaryKey != NULL, "Expected non-NULL but got NULL");
	
	memset(&context, 0, sizeof(context));
	JSONDeserializationContext_initWithFile(&context, "");
	TestCase_assert(context.jmpBuf == NULL, "Expected NULL but got %p", context.jmpBuf);
	TestCase_assert(context.status == SERIALIZATION_ERROR_OK, "Expected %d but got %d", SERIALIZATION_ERROR_OK, context.status);
	TestCase_assert(context.dispose != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readFloat != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readDouble != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readString != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBoolean != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readEnumeration != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readNextDictionaryKey != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.hasDictionaryKey != NULL, "Expected non-NULL but got NULL");
	
	memset(&context, 0, sizeof(context));
	JSONDeserializationContext_initWithJSONNode(&context, &node);
	TestCase_assert(context.jmpBuf == NULL, "Expected NULL but got %p", context.jmpBuf);
	TestCase_assert(context.status == SERIALIZATION_ERROR_OK, "Expected %d but got %d", SERIALIZATION_ERROR_OK, context.status);
	TestCase_assert(context.dispose != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.beginArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.endArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readUInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readFloat != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readDouble != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readString != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBoolean != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readEnumeration != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readBitfield64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.readNextDictionaryKey != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(context.hasDictionaryKey != NULL, "Expected non-NULL but got NULL");
	
	contextPtr = JSONDeserializationContext_createWithString("", 0);
	TestCase_assert(contextPtr != NULL, "Expected non-NULL but got NULL");
	if (contextPtr == NULL) {return;} // Suppress clang warning
	TestCase_assert(contextPtr->jmpBuf == NULL, "Expected NULL but got %p", contextPtr->jmpBuf);
	TestCase_assert(contextPtr->status == SERIALIZATION_ERROR_OK, "Expected %d but got %d", SERIALIZATION_ERROR_OK, contextPtr->status);
	TestCase_assert(contextPtr->dispose != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readFloat != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readDouble != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readString != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBoolean != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readEnumeration != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readNextDictionaryKey != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->hasDictionaryKey != NULL, "Expected non-NULL but got NULL");
	contextPtr->dispose(contextPtr);
	
	contextPtr = JSONDeserializationContext_createWithFile("");
	TestCase_assert(contextPtr != NULL, "Expected non-NULL but got NULL");
	if (contextPtr == NULL) {return;} // Suppress clang warning
	TestCase_assert(contextPtr->jmpBuf == NULL, "Expected NULL but got %p", contextPtr->jmpBuf);
	TestCase_assert(contextPtr->status == SERIALIZATION_ERROR_OK, "Expected %d but got %d", SERIALIZATION_ERROR_OK, contextPtr->status);
	TestCase_assert(contextPtr->dispose != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readFloat != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readDouble != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readString != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBoolean != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readEnumeration != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readNextDictionaryKey != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->hasDictionaryKey != NULL, "Expected non-NULL but got NULL");
	contextPtr->dispose(contextPtr);
	
	contextPtr = JSONDeserializationContext_createWithJSONNode(&node);
	TestCase_assert(contextPtr != NULL, "Expected non-NULL but got NULL");
	if (contextPtr == NULL) {return;} // Suppress clang warning
	TestCase_assert(contextPtr->jmpBuf == NULL, "Expected NULL but got %p", contextPtr->jmpBuf);
	TestCase_assert(contextPtr->status == SERIALIZATION_ERROR_OK, "Expected %d but got %d", SERIALIZATION_ERROR_OK, contextPtr->status);
	TestCase_assert(contextPtr->dispose != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->beginArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endStructure != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endDictionary != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->endArray != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readUInt64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readFloat != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readDouble != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readString != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBoolean != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readEnumeration != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield8 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield16 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield32 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readBitfield64 != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->readNextDictionaryKey != NULL, "Expected non-NULL but got NULL");
	TestCase_assert(contextPtr->hasDictionaryKey != NULL, "Expected non-NULL but got NULL");
	contextPtr->dispose(contextPtr);
}

TEST_SUITE(JSONDeserializationContextTest, testInit)
